name: sultart
favicon: null
layout_spectrum: 1
typography_spectrum: 0.008592828642576933
title: SultArt - A Collection of Art by D.R.Sult
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6ffff'
    - '#010f22'
    - '#f0b77d'
    - '#01bbfe'
    - '#b16800'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
